### ISSUE TITLE
Validator for CTD files

### ISSUE THREAD

**Issue by rrahn** [WorkflowConversion/CTDSchema#2]
Is there a validator for exported ctd files?
If not this could be really helpful to add automatic testing for exported tool descriptors and to spot errors if after version changes.

**Comment by jpfeuffer** [comment]
GKN should complain about the most dangerous errors during parsing. That's how I know ;)

**Comment by rrahn** [comment]
Well it seems that the required `ctdversion` field is not checked by GKN 😀

**Comment by jpfeuffer** [comment]
Oops well then we add it..

**Comment by chahuistle** [comment]
> Is there a validator for exported ctd files?

Not per se, but since you have a CTD and the [CTD Schema](https://github.com/WorkflowConversion/CTDSchema), you can just use [xmllint ](https://linux.die.net/man/1/xmllint) to validate the exported CTD against its schema.

Missing ´ctdVersion´ in generated CTDs is still a bug, though!

**Comment by rrahn** [comment]
Oh great, I will check xmllint.
Many thanks

**Comment by rrahn** [comment]
Ok, I tested xmllint and integrated it into our automatic testing pipeline. It would have found the missing ctdVersion, so that seems to work quite nice. 
@chahuistle Thanks again for the pointer.
